# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b267f61ef69af75fd62fcee7ba01a2c4482053f220d9b4abcb12dd11793ad16f41c6609fb11f3f5fdcc23e4e4ed73f3943fa12ffef5d39d7650d16b770fbd11

test:
  secret_key_base: 0ebb36023fed7c7a60aa1e15cb88b51c00fbb84c49d3a0a89fb6a78ebca1929b50ec23db12ad458b4215ef3e2a8ed4efe65970225638555e3944e24a8107c9b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
